### ISSUE TITLE
There is some sort of cooking issue on launch that prevents any interaction.

### ISSUE THREAD

**Issue by EnviralDesign** [EnviralDesign/UberGui#11]
On the multi-touch side there are a few problems. There is some sort of cooking issue on launch that prevents any interaction. Diving into the network fixes it, as does force cooking uberGUI with recurse=True. The multitouch is smooth for the left part of the screen, but the scrollbar works opposite to how one might expect it to.

**Comment by EnviralDesign** [comment]
@drmbt

do you have more concrete steps to reproduce? I'm not able to on my end. I setup the Touch mode, then enabled perform mode by default, restarted patch, but was able to use things fine.

**Comment by drmbt** [comment]
If I pull the current build and switch to touch mode, there is no interaction until entering the component or forcing the cook with a script. Perhaps entering perform mode causes the necessary cook; none of my tests have been in perform mode, all have been in the editor using the pane set up in your example

**Comment by EnviralDesign** [comment]
ok got ya, so you fire up the patch, and you're in the level above UberGui, in Project 1, and touch won't work in the pane to the right, until you view the internals of UG?

**Comment by drmbt** [comment]
yep, that's how to reproduce

**Comment by EnviralDesign** [comment]
issue was that the multiTouch in dat had some force cook issue. added some force cooks in logically to solve.
