### ISSUE TITLE
RFE: option to resize or disable help overlay

### ISSUE THREAD

**Issue by drmbt** [EnviralDesign/UberGui#16]
The help feature is really cool, but I could image scenarios in which it is undesired, and when interacting with a multitouch surface, the insidePanel hover triggers a bit wildly. The option to hide or scale this feature would be a nice touch (pun i guess intended?)

**Comment by EnviralDesign** [comment]
done! added to 4.0.1.

Simple tweak basically the toggle for tool tips drops the z index and kills the opacity on hover. makes it possible for someone to set the toggle with an expression if they want, to get momentary tool tips if desired.
