### ISSUE TITLE
Certain par styles set to None can't be edited directly in interface

### ISSUE THREAD

**Issue by drmbt** [EnviralDesign/UberGui#2]
Certain par types that take a string path, such as Op, OBJ, MAT, SOP. DAT, CHOP, Python, TOP. COMP etc. can't be interacted with until something has been assigned manually via the network editor parameter... once a value has been entered there, it can be double click edited as expected, but if the starting value is 'None', no interaction takes effect. This is easily reproduced by monitoring the 'Heavy' example and engaging the UI for such parameters

**Comment by EnviralDesign** [comment]
# # @drmbt This has been fixed! Thanks for the report.

I was validating par objects by using getattr() and seeing if what was returned was None or not. That was an issue for these types since they could validly return None and still be a par.

**Comment by drmbt** [comment]
Awesome, thanks for checking that out. I notice that when referencing an operator in these data types, it returns an absolute path, which is cool, but it doesn't seem like one can evaluate relative paths this way. for example, if i put op('simple_thing') into a comp, it comes back none, and things like parent() won't work either.  Is it possible to make these kinds of relative references evaluate from the position of the input OP? Even if the python reference breaks, it would be cool to be able to use relative path expressions and have them evaluate to absolute paths in UberGUI

**Comment by drmbt** [comment]
Something in this most recent push seems to have broken the rendered value for certain operator parm types. I can now type a value into UG for these types, and they seem to push the value correctly, but aren't displayed in UG:

DAT
MAT
OP
PanelCOMP
TOP
CHOP
TOP
etc

**Comment by EnviralDesign** [comment]
ahh yes combo of two issues:

A) silly line I forgot to add in an if statement and 
B) apparently parameter dat column "value" actually returns blank if an operator parameter is no valid.. so the trick was to grab the value from the "constant" column for those parameter types listed above only.
