### ISSUE TITLE
Bug with base64 encodings junking up the info DAT in 2021.10330

### ISSUE THREAD

**Issue by EnviralDesign** [EnviralDesign/UberGui#21]
![image](https://user-images.githubusercontent.com/10091486/108532171-2e784d00-729d-11eb-8e99-22cf2d1a4ba4.png)

**Comment by EnviralDesign** [comment]
@drmbt had some time to probe this further and seems to definitively be a TD bug. I'm sure we'll all have a fix for it soon and then UG will be off and running in the 2021 branch will hopefully no other issues.

https://forum.derivative.ca/t/2021-10330-win10-base64-gibberish-displayed-in-the-info-dat-from-web-render-top/173519

**Comment by EnviralDesign** [comment]
@drmbt not sure if you saw the derivative post but this will likely be fixed soon :)
Just the waiting game for now.

**Comment by drmbt** [comment]
Lol yeah, I'm waiting on a few 2021 fixes at this point. Should be any day now... really excited to get this into the 2021 build of my project I've been jamming on.

**Comment by drmbt** [comment]
Looks like this new build that dropped last night fixes some issues and creates a few others. The good news is UG seems to function in 2021 now. The bad news is that drag and drop functionality you added no longer recognizes appending new things to the list, and Op data type paramaters don't seem to be updating correctly. 

Let me know when you're digging back into this one, I have some thoughts on UX for the drag and drop stuff

**Comment by EnviralDesign** [comment]
Will do!

**Comment by EnviralDesign** [comment]
the base64 issue seems to be fixed, closing this one for now.
