### ISSUE TITLE
Default value of binding parameter

### ISSUE THREAD

**Issue by dim111** [EnviralDesign/UberGui#23]
Hi, Lucas!
Thanks for your great soft!
When I try to edit parameter, that have bind expression, the value set to default of that parameter in UberGUI interface.

**Comment by EnviralDesign** [comment]
Hi and thanks!

I've made a change now to where parameters that have a non standard par mode (read only, expression, export, bind) are non editable through UberGui, and are color coded accordingly.

This is more of a short term fix, long term I want to add ability to adjust these types of parameters where possible.
