### ISSUE TITLE
RFE: Render Color params as colors

### ISSUE THREAD

**Issue by AchimKern** [EnviralDesign/UberGui#26]
I'd be great if there was an option  to render RGB and RGBA parameters as a single "big color preview square" without any value sliders. Imho in that mode the "..." could be removed as well and clicking on the color preview would open the dropdown color picker

**Comment by EnviralDesign** [comment]
Hi Achim, thanks for the suggestion - I did what was simplest for now, which was make the color picker button's background take on the active color. the alpha channel currently is not displayed in any way, but it's as bit better.  I'll have to look into ways to show a checker background for alpha < 1.

As far as showing a full wide color picker button, going to stay away from that for the moment as the javascript parser is very structure dependent, and making that happen will require a refactor of that. I will make some new issues for those two things so I can get to it later
