### ISSUE TITLE
RFE: Ignore expr mode params  or fully support those

### ISSUE THREAD

**Issue by AchimKern** [EnviralDesign/UberGui#27]
Right now I can edit a param that is in expression mode, but that will put the param  into constant mode. But for the end user of the gui this is not transparent, so he might easily break stuff

Maybe it would be better to (optionally) ignore parameters that are in expression (or export) mode 

Or to fully support editing parameters that are in expression mode, i.e. to not change them to constant mode

**Comment by EnviralDesign** [comment]
I think a shorter term solution will be to make it a read only parameter but signify the type of read only ness by coloring the text the color of expressions, binds, and exports that TD uses.

**Comment by EnviralDesign** [comment]
eventually though I would like to add the capability, or option to edit these types too.

**Comment by EnviralDesign** [comment]
![image](https://user-images.githubusercontent.com/10091486/116152279-532cde80-a6ab-11eb-9615-92eb6c4b4ada.png)
this has been added
