### ISSUE TITLE
Scrolling Parameter RFEs

### ISSUE THREAD

**Issue by drmbt** [EnviralDesign/UberGui#3]
It would be great if part of the Style page a scroll wheel speed modifier were implemented. While I can traverse all the parameters in 'Heavy' in the Parameters Inspector with a single wheel scoll, it takes me 30 full scrolls to do the same thing in UberGUI, and a public multiplier would be helpful in dialing in a user facing interface and making it feel good  

the two finger scroll actually feels pretty good for flicks on a laptop mouse pad, but two finger scroll doesn't work unless you let up off the pad the hovers freak out a bit, which isn't the expected behavior in a browser... that very well may be a limitation of TD tho 

On a touch screen things break a bit. Increasing the Scroll Bar width makes it fairly navigable from a touch ui, but a two finger multi-touch scroll would be amazing. To that end, the ability to adjust the fill weight between the left and right part of the panel, and set the texts H orientation would be fantastic. Right now most elements can be interacted with via touch screen, but they require a double click on a new one, otherwise the parameter gets stuck on a recently interacted with parameter.  This can be fixed by using a regular mouse to engage a new parameter. Obviously touchscreen functionality isn't a priority with this UI, but I figured feedback on how its functioning with one could be helpful. 

Thanks again for releasing this, its a great contribution. Looking forward to spending some more time with it

**Comment by EnviralDesign** [comment]
@drmbt ah yes seeing these issues with touch screen - hadn't really developed on that so these are new to me.

As for the two finger scroll issue, seems that the windows driver for track pads feed data to TD this way, there might be a windows setting somewhere to disable "coasting" or w/e it's called but not too much that can do in TD about that.

I've already implemented scroll rate and scroll acceleration parameters to dial in in the config page if you want to pull the most recent.

I should be able to make style options for the text that you're talking about, and I am looking into making this as Touchscreen friendly as possible

**Comment by drmbt** [comment]
I really wish the panel chop acknowledged multi-touch... perhaps that's worth an RFE on the derivative side of things. In the meantime, perhaps a multi-touch in DAT sensing a second finger and simulating wheel interactions could bridge the gap? two finger drag could engage the interactMouse() method as a wheel simulation, and an 'Active' toggle on the config page could simply bypass multi-touch mode if a user doesn't need/want that to take any resources

**Comment by EnviralDesign** [comment]
@drmbt hey I've done some code refactoring, and added in official touchscreen support as a toggle in the config page. So users just need to choose whether the UI should respond to Touch input or Mouse input.

I'll update the readme on how the control scheme works for that, it's a bit different, but simple enough to learn.

Horizontal position for texts is now supported, as well as a way to move the vertical split that was previously always at 50/50.

**Comment by drmbt** [comment]
Style features are great, thanks for adding them! It seems this build has broken the functionality of the scroll bar in mouse mode though, probably while formatting it for multi-touch. There are also some errors being returned when double clicking pageHeaders, sometimes its the troubleshooting exception, but sometimes it catches an attribute error in project1/container_UG_V4/field/field

On the multi-touch side there are a few problems. There is some sort of cooking issue on launch that prevents any interaction. Diving into the network fixes it, as does force cooking uberGUI with recurse=True. The multitouch is smooth for the left part of the screen, but the scrollbar works opposite to how one might expect it to.  

The way picking works seems to be really inconsistent; I suspect this has something to do with you're checking for IsPickingDataValid and didMove. The result is that certain data types like pulse and momentary can't be triggered at all from multitouch, and the interface often gets stuck thinking you're still interacting with the left half of the ui when you're trying to work with individial parameters on the right. Parameters still need to be double clicked to engage with mtouch, which is unintuitive, and doesn't work very consistently so it feels clunky. I suspect this is because unlike using a touchscreen on regular sliders, this UI needs to know what is being hovered over before it engages, and that extra layer of abstraction is borking something

Touchmode de-activates the ability to interface with the GUI via a mouse, which is problematic for mixed mode use cases... even when interacting with a touch screen, I'm almost always going to also want to be able to use a mouse as well. I see no reason to deactivate panelexec_interact_mouse_scroll while in Touch mode for example, but I suspect the ultimate solution lies in a unified mode using the mtouchinDAT with Include Mouse activated, possibly combined with a panel chop. I know this gets messy, and is one of the reasons touch developement in TD is so difficult. Just figured I'd report my experience, I think for this to feel good as a touchscreen interface, one needs to be able to adjust slider values with a single click touch interaction. Double clicking will be too difficult to consistently engage an interaction without the logic being confused by subtle movements due to the inaccuracy of a user's second click

**Comment by EnviralDesign** [comment]
@drmbt awesome thanks for the feedback! broken these out to separate issues, some will try to tackle tonight, others will try to bundle into a later 4.1.0. Though that might happen sooner than later too, will see.
