### ISSUE TITLE
RFE: Allow Bind mode

### ISSUE THREAD

**Issue by AchimKern** [EnviralDesign/UberGui#33]
Hi Lucas

I appreciate the read-only mode for parameters in expression mode. 

But imho bind mode should NOT be read-only. In my testing it worked perfectly (I was binding to a dependDict holding parameter presets)

Could you please re-enable parameters in bind mode (or provide a setting which pars modes will be read-only)

Also, is there a way to set the text colors for expression, read only and export mode? 
Thanks!

**Comment by EnviralDesign** [comment]
@AchimKern ya I acted a bit quickly on the last wave - someone else had issues with binding, but I have not for the life of me been able to reproduce it and sounds like it's good on your end too.

I've also added color styling parameters for all of the parmode types, bind is not read only, but still has a style option.

**Comment by AchimKern** [comment]
thanks!
