### ISSUE TITLE
Menu width doesn't take scrollbar width into account

### ISSUE THREAD

**Issue by AchimKern** [EnviralDesign/UberGui#35]
Now that the popup menu scrollbar width can be configured, the dropdown menu extends across the width of the parameter if you increase the scrollbar width

**Comment by EnviralDesign** [comment]
@AchimKern could you attach a screenshot showing how it looks on your end? or provide some parameters to recreate? Want to make sure the thing I'm seeing is what you're talking about.

Thanks!

**Comment by AchimKern** [comment]
I'm sorry. Must have been my bug. can't reproduce. please disregard
