### ISSUE TITLE
RFE: Handle header type pars

### ISSUE THREAD

**Issue by AchimKern** [EnviralDesign/UberGui#36]
I think I only have one RFE remaining. Currently "header type" pars are rendered as editable strings.  Imho these should get their own (header like) styling. Or, as a quick fix, those could be just rendered as headers.

**Comment by EnviralDesign** [comment]
Could you elaborate on what you're referring to? Not quite sure - headers in UberGui as I've self described them ? Those have their own styling options in the Style page and I can't seem to text highlight them or anything.. but I suspect you're talking about something else - is this related to the newest TD builds in 2021?

**Comment by AchimKern** [comment]
Talking about custom pars of type header I.e. 
page.appendHeader(name, label=None, order=None, replace=True)


Those type of custom parameters seem to be rendered as strings in uberGUI

I was thinking that those should be rendered in a way similar to how you render page names : as headers

Ideally with their own style parameters so they look different from page names (smaller font,...)


Does that make more sense ?

**Comment by EnviralDesign** [comment]
Oooh, these are new to me.
Will look at getting these integreated.

**Comment by EnviralDesign** [comment]
ok this has been fixed. Header parameter types act just like standard page name headers.
