### ISSUE TITLE
Field editing binded pars

### ISSUE THREAD

**Issue by AchimKern** [EnviralDesign/UberGui#37]
Hi Lucas 

I think this might be the same issue as someone else reported. Editing binded parameters via slider/buttons works perfectly, 
the issue is when you double click to edit a par, you get the value of the "constant mode" in the field

Open your demo file, load the custom OP example

drag the Bind slider to e.g: 0.5

double click the slider/value to edit the value manually

-> the field will show 0.0 (and NOT 0.5)

**Comment by EnviralDesign** [comment]
awesome thanks for detailed steps - will get this fixed soon.

**Comment by EnviralDesign** [comment]
fixed
