### ISSUE TITLE
undocumented upper case requirement for page names

### ISSUE THREAD

**Issue by drmbt** [EnviralDesign/UberGui#5]
latest stable build, fresh pull from the git:

creating a new base with customPars and pointing the i/o from UberGUI returns a blank screen. It would appear that UberGUI requires an isupper() condition to be met in the name of customPages, this doesn't seem to be documented anywhere, but should be noted if anyone expects to plug pre-existing components into the GUI without some amount of confusion

I'm not sure why this is absolutely necessary, but maybe its in place to prevent something else from breaking. Would be great if all caps wasn't necessary, as it would require a lot of work, albeit rather simple renaming, to integrate this into a system that doesn't already have those naming conventions in place

**Comment by EnviralDesign** [comment]
just pushed another build that gives a menu parameter for choosing whether or not to filter by all custom pages (now default) or the previous scheme which was really just legacy from my own implementation in GeoPix.

I might add another later for providing the user more flexibility, maybe through space or comma separated page names in another field!

**Comment by drmbt** [comment]
Awesome! The ability to preserve tabbed pages vs the current function of  appending them to a single scrollable UI would be helpful as well
